### ISSUE TITLE
ドロップボックス自動保存モードを作成する

### ISSUE THREAD

**Issue by qh73xe** [kikuchiken-waseda/mri-vuewer.ver2#7]
## ユーザ動作
- [x]  設定画面から dropbox への自動保存 をチェックする
- [x] vuewer 画面からの遷移時に dropbox へ自動送信を行う

## TODO
- [x] 設定画面に自動保存を行う選択肢を作成する
- [x] vuewer 画面からの遷移を検出する: ブラウザ系動作, router 系動作
- [x] 画面遷移が検出されたら, 現状のデータをキャッシュ化し dropbox に送信する

**Comment by qh73xe** [comment]
機能実装はしゅうりょう
